name: PHP Composer

on:
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: build
      uses: github-actions-x/hugo@master
    - name: push
      uses: dciborow/commit@0.0.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: ${{ github.ref }}
        commit-message: 'publish'
        force-add: 'true'
        force-push: 'true'
        name: commiter name
        email: my.github@email.com 
