name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        #persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        #fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        ref: ${{ github.ref }}
        
    - name: compile
      run: echo Hi. >> notes.txt
      working-directory: .
    
    #- uses: actions-go/push@master
    # with:
    #    commit-message: '[Auto] update pre-puilt dist packages'
    #    remote: origin


    - name: build
      uses: github-actions-x/hugo@master
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'origin'
        commit-message: 'publish'
        force-add: 'true'
        name: commiter name
        email: my.github@email.com 
